#!/usr/bin/env bash
set -Eeuo pipefail

pot="dory-extensions.pot"

rm -f ${pot}
touch ${pot}

potfiles_to_extract=(
    dory-audio-tab/dory-extension/dory-audio-tab.glade
    dory-image-converter/data/dory-image-resize.ui
    dory-image-converter/data/dory-image-rotate.ui
    dory-pastebin/data/dory-pastebin-configurator.ui
    dory-repairer/src/encoding-dialog.ui
    dory-repairer/src/repair-dialog.ui
    dory-share/interfaces/share-dialog.ui
)

potfiles_extracted=( )
for file in "${potfiles_to_extract[@]}"; do
    intltool-extract --type=gettext/glade "$file"
    potfiles_extracted+=( "${file}.h" )
done

potfiles_c=(
    dory-dropbox/src/*.c
    dory-dropbox/src/*.h
    dory-fileroller/src/*.c
    dory-fileroller/src/*.h
    dory-image-converter/data/*.ui.h
    dory-image-converter/src/*.c
    dory-image-converter/src/*.h
    dory-preview/src/*.c
    dory-preview/src/libdory-preview/*.c
    dory-preview/src/libdory-preview/*.h
    dory-repairer/src/*.c
    dory-repairer/src/*.h
    dory-repairer/src/*.ui.h
    dory-share/interfaces/*.ui.h
    dory-share/src/*.c
    dory-share/src/*.h
)
potfiles_python=(
    dory-audio-tab/dory-extension/*.glade.h
    dory-audio-tab/dory-extension/*.py
    dory-compare/src/*.py
    dory-emblems/dory-extension/*.py
    dory-media-columns/*.py
    dory-pastebin/*.py
    dory-pastebin/src/*.py
    dory-pastebin/data/*.ui.h
    dory-seahorse/tool/dory-seahorse-tool
    dory-terminal/src/*.py
    generate_desktop_files
)
potfiles_javascript=(
    dory-preview/src/js/*/*.js
)

xgettext --language=C           --keyword=_ --keyword=N_ --keyword=g_dngettext:2,3 --output="$pot" --join-existing "${potfiles_c[@]}"
xgettext --language=JavaScript  --keyword=_ --keyword=N_ --output="$pot" --join-existing "${potfiles_javascript[@]}"
xgettext --language=Python      --keyword=_ --keyword=N_ --output="$pot" --join-existing "${potfiles_python[@]}"
xgettext --language=Desktop                                --output="$pot" --join-existing dory-seahorse/data/*.dory_action

rm -f "${potfiles_extracted[@]}"
